# Generated by Django 4.2.3 on 2023-09-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="validate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=100)),
                ("mail", models.EmailField(max_length=254)),
                ("qualification", models.CharField(max_length=100)),
                ("percentage", models.IntegerField()),
                ("place", models.CharField(max_length=100)),
                ("phone", models.BigIntegerField()),
            ],
        ),
    ]
